### ISSUE TITLE
[1.12] [spectritemod-1.3.2-1.12] Periodical Server lag issues

### ISSUE THREAD

**Issue by fampat** [Samuel-Harbord/SpectriteMod#7] opened 2017-07-18 20:45 UTC
Hi!

ive tried the new version, the biggest problem i found (and that makes it unusable right now) is a periodical lag, one every minute the server lags about 5 sec behind, all players do complain about this lag :(

For test purpose, after removing this this mod and creating a new world, the lags also stopped.

https://pastebin.com/6VKt0qy4

It could also be reproducable by only hafing forge-1.12-14.21.1.2413-universal and this mod... then create a new world and watch the console, it creates a lag issue every minute

https://pastebin.com/b2BEKu0v

**Comment by Flashfyre** [comment] 2017-07-18 21:08
Does this happen in version 1.2.0? I did change some things about the dungeon spawn in the newest version but they should only improve the performance if anything. The dungeon should only build once so it's very strange to me that this is a continuing issue.

**Comment by Flashfyre** [comment] 2017-07-18 21:24
I found the very likely cause of this bug, thank you for pointing it out. I can't believe I forgot to uncomment the replacement of the Spectrite Dungeon spawn coords with 0,0 for testing...

**Comment by Flashfyre** [comment] 2017-07-18 21:32
Update: This did not fix the lag issue, I will continue to look into it. Though, if you could, please try the new version and tell me if there is any improvement.

**Comment by fampat** [comment] 2017-07-18 21:48
just tested 
spectritemod-1.3.3-1.12.jar

issue persist :(

**Comment by Flashfyre** [comment] 2017-07-18 21:52
It's very weird that this doesn't seem to be happening on the MMD Dev server that uses my mod, and it has dozens of other mods too... Knowing if this is also an issue in 1.2.0 would also be very helpful.

**Comment by fampat** [comment] 2017-07-18 21:56
no, ive used your 1.2x mod until ive installed 1.3, there was no lag issue

**Comment by Flashfyre** [comment] 2017-07-18 21:57
Thank you, that narrows it down a lot.

**Comment by fampat** [comment] 2017-07-18 22:02
Also ive noticed that if the world id created prior adding 1.3, the lag also doesnt exist, seems like it has something to do with stuff added while the world is being created

**Comment by Flashfyre** [comment] 2017-07-18 22:05
Have you tried creating a new world in 1.3.3?

**Comment by fampat** [comment] 2017-07-18 22:11
yes, in fact, only tested that

**Comment by Flashfyre** [comment] 2017-07-18 22:11
Alright, thanks. I'm still looking for the cause.

**Comment by Flashfyre** [comment] 2017-07-18 22:12
One more thing you could try that would greatly help, could you try creating a new world with the Generate Spectrite Dungeon config option turned off?

**Comment by Flashfyre** [comment] 2017-07-18 22:14
Oh. Nevermind. I... think I found the cause...

**Comment by Flashfyre** [comment] 2017-07-18 22:17
Definitely the cause... It will be fixed in 1.3.4 which should be up within 15m. I can't believe I did something so dumb.

**Closed as completed by Flashfyre** 2017-07-18 22:17 UTC
Labels: bug

**Comment by fampat** [comment] 2017-07-18 22:19
hooray, we love this mod, iam glad you found it (hopefully) :)

**Comment by Flashfyre** [comment] 2017-07-18 22:21
Ohh I did... I was originally going to make a dimension out of Spectrite but I cancelled the idea due to the large amount of lag caused by a dimension with only animated blocks. Unfortunately, I didn't think about it generating without anyone actually going to it. It was generating...
